### ISSUE TITLE
gnuplot upgrade

### ISSUE THREAD

**Issue by mooreniemi** [mooreniemi/graph-function#8]
```
ruby lib/tdm.rb
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib                                    |
  Referenced from: /usr/local/bin/gnuplot
  Reason: image not found
Tdm vs IfElse: |=============================================================================================|
Tdm vs IfElse: |=============================================================================================|
/Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:104:in `write': Broken pipe (Errno::EPIPE)
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:104:in `<<'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:104:in `initialize'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/graph-function-0.1.7/lib/graph/function/comparison.rb:18:in `new'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/graph-function-0.1.7/lib/graph/function/comparison.rb:18:in `block in of'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:76:in `block in open'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:75:in `popen'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/gnuplot-2.6.2/lib/gnuplot.rb:75:in `open'
	from /Users/Alex/.rvm/gems/ruby-2.2.2/gems/graph-function-0.1.7/lib/graph/function/comparison.rb:17:in `of'
	from lib/tdm.rb:67:in `<main>'
```

**Comment by mooreniemi** [comment]
this worked:

```
brew upgrade gnuplot
==> Upgrading 1 outdated package, with result:
gnuplot 5.0.5
==> Upgrading gnuplot
==> Installing dependencies for gnuplot: libpng, libtiff, gd
==> Installing gnuplot dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.26.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.26.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.26: 26 files, 1.2M
==> Installing gnuplot dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.7.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtiff-4.0.7.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.7: 248 files, 3.3M
==> Installing gnuplot dependency: gd
==> Downloading https://homebrew.bintray.com/bottles/gd-2.2.3_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gd-2.2.3_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/gd/2.2.3_1: 35 files, 1.1M
==> Installing gnuplot
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz
==> Downloading from https://superb-dca2.dl.sourceforge.net/project/gnuplot/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnuplot/5.0.5 --with-readline=/usr/local/opt
==> make
==> make install
🍺  /usr/local/Cellar/gnuplot/5.0.5: 47 files, 2.5M, built in 1 minute 1 second
```
